### ISSUE TITLE
Controlling the amount of correct captions

### ISSUE THREAD

**Issue by furkanbiten** [AlexKuhnle/ShapeWorld#17]
Hi Alex,

Great work! I was just curious if you could choose the amount of correct captions to produce. For example, I would like to have all correct captions for certain images but all incorrect captions for others. 

I hope I didn't miss something obvious.

**Comment by AlexKuhnle** [comment]
Hi,
thanks, glad you like it. You may have seen that the `CaptionAgreementDataset` has an argument `correct_ratio=0.5`. The easiest way to achieve all in-/correct captions is probably to just generate two datasets, one with a ratio of 1.0, the other with 0.0. If you need them mixed, you could still mix them afterwards. Alternatively, you could adapt the 1-2 lines in the code where the expected correctness per instance is determined, but I guess the first option is easier. Hope that helps.

**Comment by furkanbiten** [comment]
Holy, that was fast!

Thanks for the answer. Exactly what I was looking for.
