### ISSUE TITLE
No module named mrs_load

### ISSUE THREAD

**Issue by furkanbiten** [AlexKuhnle/ShapeWorld#18]
Hi Alex,

Thank you for the analyzer part. However, whenever I try to run "mrs.convert_to(cls=Dmrs, copy_nodes=True)", it throws an No module named mrs_load error inside analyzer.mrs. 

Also, I think in analyzer.analyzer in line 239, there is no dmrs_list created. I fixed it just by creating dmrs_list = list(). But I thought you would like to know.

**Comment by AlexKuhnle** [comment]
Hehe, you found it already. I had added but not tested it yet, so I'm not surprised there may be something missing (ACE doesn't run on a Windows machine, even in the Ubuntu subsystem, it seems). I'll look into it.

**Comment by furkanbiten** [comment]
I was almost about to lose my mind on ACE :) What a pain :) (For those having problem, put ACE executable on /usr/bin and chmod 777 so that there wont be permission issues). 

So, I downloaded the latest commit on analyzer and here are some weird behaviour I am getting, maybe you can help me with those. For example, when I am running `analyze = analyzer.Dmrs_analyzer(), analyze([''A pentagon is not smaller than a triangle.''])`, I am getting `[None]`. 

 Another thing is that if I try to use analyze functionality, it throws an error `"unsupported type for sortinfo"`. I believe this error is coming from pydmrs. So, to circumvent the problem, I was using the parse function from `from pydmrs.pydelphin_interface` and then converting the `ListDmrs` object to `Dmrs` object from shapeworld and then using analyze2 from analyzer. However, even with that I am getting None as caption. I am assuming getting the None is dependent on analyze2() function, since it is used on analyze as well. That is so far I got :D

**Comment by AlexKuhnle** [comment]
I don't think it should be necessary to move ACE -- I don't have to when I clone the repo and run it from scratch.

I fixed the "unsupported type for sortinfo" problem -- annoying Python relative import problem.

The parsing process is unfortunately not perfect, so a few sentences which should be part of the "ShapeWorld semantic space" may not parse. Let me know which sentences don't work for the most recent version, and I can see whether it can be fixed.

**Comment by AlexKuhnle** [comment]
Oh, and let's do that in another issue, so that people can find the problem under a meaningful name, since this one should be solved now.

**Comment by furkanbiten** [comment]
> 
> 
> Oh, and let's do that in another issue, so that people can find the problem under a meaningful name, since this one should be solved now.

Makes sense. Opening a new one.

**Comment by furkanbiten** [comment]
> 
> 
> I don't think it should be necessary to move ACE -- I don't have to when I clone the repo and run it from scratch.
> 
> I fixed the "unsupported type for sortinfo" problem -- annoying Python relative import problem.
> 
> The parsing process is unfortunately not perfect, so a few sentences which should be part of the "ShapeWorld semantic space" may not parse. Let me know which sentences don't work for the most recent version, and I can see whether it can be fixed.

Oh, thanks for the fix on "unsupported type for sortinfo" :) Almost forgot...
