### ISSUE TITLE
Sentence structure seems broken in Selection Dataset

### ISSUE THREAD

**Issue by furkanbiten** [AlexKuhnle/ShapeWorld#22]
Hi Alex, 

Me again :) Hope everything is going well. I was trying to use Selection Dataset to generate examples however, it seems there are some discrepencies. For example, for the "x-two" relationship, I sometimes get sentences such as "The left shape is a magenta circle." or for the "x-max", I get "The leftmost shape is a circle." This behaviour is repeated for "proximity" and "y" relationships as well. 

From [examples](https://rawgit.com/AlexKuhnle/ShapeWorld/master/examples/agreement/selection-full/data.html) I see, the correct behaviour should be "the left (insert color or shape) shape is (insert correct attribute)". 

What do you think? Am i missing something? Is this an expected behaviour? 

Thanks as usual :) 

EDIT: Markups was wrongly used so whole message wasn't understandable.

**Comment by furkanbiten** [comment]
Apparently it was because of allow_empty_scope=True by default which was the reason for the behaviour above. 
Everytime I am diving more into the code I am suprised more and more by the flexibility and controllability it provides. 

PS: [This](https://github.com/AlexKuhnle/ShapeWorld/blob/08c542a4ea98b2b7f41a2fb1cfdf8bb8fbe17b28/shapeworld/datasets/agreement/relational_single_attribute.py#L3) needs to import UniqueTypeCaptioner. I found out when I was testing the SingleAttribute generation.

**Comment by AlexKuhnle** [comment]
Hey,

You mean that in the examples it never contains just "shape", but always some more detailed specification? Yes, that would be the option related to that. Seems like I've changed the default but haven't re-generated the examples at some point. Anyway, good you found the problem.

The `RelationalSingleAttributeDataset` comes from a very recent PR (one aspect which couldn't be controlled so far was that objects are always described by the same one attribute, which was the use case here). @dschaehi, mind fixing this import?

**Comment by furkanbiten** [comment]
I wanna close off by making sure that we are on the same page, just in case someone has found its way to this issue (What are the chances but anyway..)

In the selector dataset [examples](https://rawgit.com/AlexKuhnle/ShapeWorld/master/examples/agreement/selection-full/data.html), there is a pattern in the sentence which follows  "the left/right/upper/lower (insert color or shape) shape is (insert correct attribute)". 

If you allow_empty_scope, i.e. setting it True, you can have sentences with the pattern of "the left shape is (insert correct attribute)" or "the rightmost shape is (insert correct attribute)". 

@AlexKuhnle Hope this was clearer than before :)

**Comment by dschaehi** [comment]
> Hey,
> 
> You mean that in the examples it never contains just "shape", but always some more detailed specification? Yes, that would be the option related to that. Seems like I've changed the default but haven't re-generated the examples at some point. Anyway, good you found the problem.
> 
> The `RelationalSingleAttributeDataset` comes from a very recent PR (one aspect which couldn't be controlled so far was that objects are always described by the same one attribute, which was the use case here). @dschaehi, mind fixing this import?

@AlexKuhnle: Sure, I made a pull request.
