### ISSUE TITLE
module object is not callable

### ISSUE THREAD

**Issue by RylanSchaeffer** [AlexKuhnle/ShapeWorld#31]
When I follow the instructions in the README,

```
from shapeworld import dataset

dataset = dataset(dtype='agreement', name='multishape')
```

I get the following error: `TypeError: 'module' object is not callable`.  Are the instructions correct?

As a workaround, I instead tried:

```
ds = shapeworld.dataset.Dataset.create(dtype='agreement', name='multishape')
```

But then I get the error:

```
ModuleNotFoundError: No module named 'shapeworld.datasets.agreement.multishape'
```

**Comment by RylanSchaeffer** [comment]
This is bizarre. I cloned the repo with `git clone --recursive https://github.com/AlexKuhnle/ShapeWorld.git` but I didn't receive all the data under `shapeworld/datasets/`:

![image](https://user-images.githubusercontent.com/8942987/141012414-ead98ae8-bd7f-4bfd-ac7c-d762015bc635.png)

**Comment by RylanSchaeffer** [comment]
I just cloned again and got the same outcome. What's going on :thinking:

**Comment by RylanSchaeffer** [comment]
Ok somehow I cloned from an old commit. All good now!

**Comment by AlexKuhnle** [comment]
No worries... :-)
