### ISSUE TITLE
Clarification of dtype and name?

### ISSUE THREAD

**Issue by RylanSchaeffer** [AlexKuhnle/ShapeWorld#32]
The README provides examples for several types of dtype and name, but I can't find documentation anywhere about (1) what the complete set of options is and (b) what each of them mean.

How do I generate all possible images uniformly at random?

**Comment by RylanSchaeffer** [comment]
Inside `generators`, there's a `RandomAttributesGenerator`. What dtype and name do I choose to use that?

**Comment by AlexKuhnle** [comment]
The configs and code is the best documentation here, unfortunately.
- [Configs](https://github.com/AlexKuhnle/ShapeWorld/tree/master/configs/agreement) are used for minor variations of a specific dataset type (agreement dataset types here, but check others if interested).
- [Dataset types](https://github.com/AlexKuhnle/ShapeWorld/tree/master/shapeworld/datasets/agreement) are simple classes which combine world generator and captioner modules. By looking at the few types available, you should get an idea for what other setups are possible (again, agreement dataset types, but check others if interested).
- For [world generators](https://github.com/AlexKuhnle/ShapeWorld/tree/master/shapeworld/generators), there are not many options, but you could of course implement your own.
- You can check the [captioners](https://github.com/AlexKuhnle/ShapeWorld/tree/master/shapeworld/captioners) for what arguments, if any, they expect. Specifying your own captioner is not straightforward, unfortunately.

**Comment by AlexKuhnle** [comment]
Assume this can be closed.
