### ISSUE TITLE
Add wget to setup.py

### ISSUE THREAD

**Issue by tomsherborne** [AlexKuhnle/ShapeWorld#4]
Hi Alex,

I wanted to suggest that the `wget` package is added to the requirements in `setup.py` as I've found new clones of the repo can't generate new data with `generate.py` without it. 

I would do this as a PR but I'm only allowed one fork from yours and I'm not up to date/I've made other (minor) changes that you don't need.

Thanks :)

**Comment by AlexKuhnle** [comment]
I added a "[full]" and "[full-gpu]" installation mode, which includes wget and tensorflow(-gpu).
