### ISSUE TITLE
Reading pre-loaded datasets tries to open `world_features` unsuccessfully

### ISSUE THREAD

**Issue by tomsherborne** [AlexKuhnle/ShapeWorld#9]
[Not urgent]

Hi Alex,

I've noticed that if you open a dataset that has saved the ResNet features using `generate()` not `tf_util.batch_records()` then there is an exception thrown as `deserialize_value()` tries to open `world_features.txt` (the offending line is 436 in `dataset.py`). This doesn't seem to be a useful file as the full features aren't saved in non-TFRecord form so a condition to ignore them could be included. 

 I know you require the generation of TFRecords for the ResNet features but in cases such as designing a manual object detector (such as what I am doing now) and I need the world_model I have to use the `generate()` call.

Hope this helps!

**Comment by AlexKuhnle** [comment]
This should be fixed now, however, it's not (yet) optimal, since the data is serialized as a txt file, which for these feature files doesn't make so much sense. Anyway, I'll close this for now, and might add some improvements later on.
